### PR TITLE
Update DataEthicsChecklistAuthorResponse

### PR DESCRIPTION
**Pull request by amyrejoint**

### CODE REVIEW

**Review by HuwWDay — APPROVED** [review]

**Comment by HuwWDay** [comment]
@ninadicara Amy has changed some text formatting and suddenly github is having a hissy fit. It says the branch conflicts are too complex to be reviewed on web browser, any ideas?

**Comment by ninadicara** [comment]
@HuwWDay I'll have a look now :)

**Comment by ninadicara** [comment]
It looks like it wasn't allowing you to address them in the browser because the file didn't have `.md` at the end so it didn't know to handle it like a markdown document. I've added that and also just put a few little markdown touches in (`>` for nice quotes and `---` for a horizontal line at the end). 
The `*` for italics also will only work within a single line on the doc so you have to top and tail each sentence with it if that makes sense! 
Merging now!

**Comment by amyrejoint** [comment]
Ahhh thanks so much Nina, we'd talked about the .md already this morning
and it immediately fell out of my brain!

**Pull request merged**
